import time

def main(type):
	if type == "AttackBlock":
		print("security hole attack blocked")
		print("security hole attack blocked")
		print("ThinkPHP attack blocked")
		print("security hole detected")
		print("security hole repair")
		print("security hole attack blocked")
		print("SYN Flood attack detected")
		print("security hole attack blocked")
		print("security hole detected")
		print("security hole attack detected")
		print("security hole attack detected")
		print("security hole repair")
		print("security hole attack blocked")
		print("Path traversal attack blocked")
		print("security hole attack blocked")
		print("virus detected")
		print("UDP Flood detected")
		print("IP 122.162.812.219 access blocked")
		print("virus deleted")
		print("virus download blocked")
		print("security hole attack blocked")
		print("f5 attack detected")
		print("security hole attack detected")
		print("security hole attack detected")
		print("security hole attack detected")
		print("virus detected")
		print("virus deleted")
		print("security hole repair")
		print("security hole attack blocked")
		print("security hole attack blocked")
		print("HTTP post flood attack detected")
		print("security hole attack blocked")
		print("virus detected")
		print("security hole attack blocked")
		print("ThinkPHP attack blocked")
		print("IP 194.723.183.229 access blocked")
		print("DNS amplification attack detected")
		print("TCP flood attack detected")
		print("security hole attack detected")
		print("TCP flood attack detected")
		print("virus deleted")
		print("virus install file deleted")
		print("virus infection file deleted")
		print("virus detected")
		print("TCP flood detected")
		print("virus deleted")
		print("HTTP get flood attack detected")
		print("security hole attack detected")
		print("security hole repair")
		print("HOIC attack detected")
		print("HOIC attack detected")
		print("HOIC attack detected")
		print("security hole attack blocked")
		print("virus install blocked")
		print("LOIC attack detected")
		print("HOIC attack detected")
		print("f5 attack detected")
		print("ThinkPHP attack blocked")
		print("DNS amplification attack detected")
		print("LOIC attack detected")
		print("LOIC attack detected")
		print("IP 113.292.689.191 access blocked")
		print("HOIC attack detected")
		print("HOIC attack detected")
		print("LOIC attack detected")
		print("HOIC attack detected")
		print("HOIC attack detected")
		print("IP 43.292.183.26 access blocked")
		print("Nginx stopped")
		print("ThinkPHP attack blocked")
		print("UDP flood attack detected")
		print("security hole attack blocked")
		print("HOIC attack detected")
		print("security hole attack blocked")
		print("security hole attack blocked")
		print("security hole attack detected")
		print("security hole attack blocked")
		print("virus install blocked")
		print("virus install blocked")
		print("TCP flood attack detected")
		print("virus install file deleted")
		print("security hole attack blocked")
		print("security hole searching")
		print("security hole attack detected")
		print("HOIC attack detected")
		print("security hole attack blocked")
		print("security hole attack detected")
		print("security hole detected")
		print("TCP flood attack detected")
		print("HTTP post flood attack detected")
		print("security hole repair")
		print("security hole attack blocked")
		print("virus detected")
		print("virus install file blocked")
		print("virus deleted")
		print("security hole attack blocked")
		print("security hole detected")
		print("security hole repair")
		print("TCP flood attack detected")
		print("security hole attack blocked")
		print("UDP flood attack detected")